// Generated by CoffeeScript 1.5.0
(function() {
  var Observable, SelectModel, SelectView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Observable = (function() {

    function Observable(attrs) {
      this.attrs = attrs;
      this._callbacks = {};
    }

    Observable.prototype.on = function(event_name, cb) {
      return this._callbacks[event_name] = cb;
    };

    Observable.prototype.cl = function(event_name, args) {
      return this._callbacks[event_name].call(null, args);
    };

    return Observable;

  })();

  SelectModel = (function(_super) {

    __extends(SelectModel, _super);

    function SelectModel() {
      SelectModel.__super__.constructor.apply(this, arguments);
    }

    SelectModel.prototype.filter = function(term) {
      return this.cl('filtered', [term]);
    };

    SelectModel.prototype.selection = function(value) {
      this.selection = value;
      return this.cl('selected', value);
    };

    return SelectModel;

  })(Observable);

  SelectView = (function() {

    function SelectView(node) {
      this.node = node;
    }

    SelectView.prototype.render = function(items) {
      var res;
      res = $.map(items, function(i) {
        return "<li>" + i + "</li>";
      });
      return this.node.html(res.join(''));
    };

    return SelectView;

  })();

  jQuery(function() {
    var data, model, view;
    data = ['one', 'two', 'three'];
    model = new SelectModel({
      data: data
    });
    view = new SelectView($('#result'));
    model.on('filtered', function(items) {
      return view.render(items);
    });
    model.on('selected', function(value) {
      return $('#selection').html(value);
    });
    $('#autocomplete').keyup(function() {
      return model.filter($(this).val());
    });
    return $('#autocomplete').blur(function() {
      return model.selection($(this).val());
    });
  });

}).call(this);
