// Generated by CoffeeScript 1.5.0
(function() {
  var SelectModel, data, sm;

  SelectModel = (function() {

    function SelectModel(attrs) {
      this.attrs = attrs;
      this._callbacks = {};
    }

    SelectModel.prototype.on = function(event_name, cb) {
      return this._callbacks[event_name] = cb;
    };

    SelectModel.prototype.filter = function(term) {
      return this._callbacks['filtered'].call(null, [term]);
    };

    SelectModel.prototype.selection = function(value) {
      this.selection = value;
      return this._callbacks['selected'].call(null, value);
    };

    return SelectModel;

  })();

  data = ['one', 'two', 'three'];

  sm = new SelectModel({
    data: data
  });

  sm.on('filtered', function(items) {
    var res;
    res = $.map(items, function(i) {
      return "<li>" + i + "</li>";
    });
    return $('#result').html(res.join(''));
  });

  sm.on('selected', function(value) {
    return $('#selection').html(value);
  });

  sm.filter('term');

  jQuery(function() {
    $('.autocomplete').keyup(function() {
      return sm.filter($(this).val());
    });
    return $('.autocomplete').blur(function() {
      return sm.selection($(this).val());
    });
  });

}).call(this);
