// Generated by CoffeeScript 1.5.0
(function() {

  (function($) {
    return $.fn.select2 = function() {
      return $(this).each(function() {
        var cnt;
        return cnt = new window.SelectController(this);
      });
    };
  })(jQuery);

}).call(this);
